stages:
  - build
  - push

image: microsoft/dotnet:8.0-x64  # Base image for building .NET 8 app

variables:
  DOTNET_VERSION: 8.0  # Adjust if using a different .NET version
  DOCKERFILE_PATH: ./Dockerfile  # Path to your Dockerfile
  IMAGE_NAME: ${CI_PROJECT_NAME}:${CI_COMMIT_SHORT_SHA}  # Image name based on project and commit

services:
  - docker:dind  # Use Docker-in-Docker for build and push stages

build:
  only:
    - master
  stage: build
  script:
    # - dotnet publish --configuration Release /output  # Publish app to output folder
    - docker build -t $IMAGE_NAME $DOCKERFILE_PATH  # Build image using dynamic name

push:
  stage: push
  dependencies:
    - build  # Wait for build stage to complete
  script:
    - docker login registry.gitlab.com -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    - docker push $IMAGE_NAME

# only:
#   - master  # Run pipeline only for pushes to the master branch (adjust as needed)
