name: Backend Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      working-directory: .
      run: docker build . -t tritx/base-admin:latest

    - name: Log into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image to Docker Hub
      run: docker push tritx/base-admin:latest
    
    - name: Pull the image to VM Digital Ocean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: | 
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/base-admin:latest
          docker stop base-admin || true
          docker rm base-admin || true
          docker run -d -p 1998:8080 --name base-admin ${{ secrets.DOCKERHUB_USERNAME }}/base-admin:latest

